### ISSUE TITLE
Upgrade GemFire/Geode dependencies to the latest GA release

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/gemfire#9]
As a developer, I'd like to upgrade to the latest gemfire GA dependencies.

**Comment by artembilan** [comment]
Note: the latest is already Spring Data Kay which is Spring Framework 5.0 base line.
I'm afraid the previous Spring Data Gemfire might not be compatible with the latest Geode.

**Comment by jxblum** [comment]
@sabbyanandan - What sort of update are you looking for?

@artembilan - What do you mean by following?  

> I'm afraid the previous Spring Data GemFire might not be compatible with the latest Geode.

Both _Spring Data GemFire_ and _Spring Data Geode_ are part of the _Spring Data Release Train_ now, as of **Kay**.

I will be publishing a blog post soon on this, but essentially, _Spring Data GemFire_ **Kay** is based on Pivotal GemFire 9.1.0, which is itself based on Apace Geode 1.2.0.  _Spring Data Geode_ **Kay**, is based on Apache Geode 1.2.1.

One of my quote unquote goals of _Spring Data GemFire_/_Spring Data Geode_ is that the dependencies are interchangeable, and today, that is true for SDG^2 **Kay**.

Hope this helps. Let me know if you have more questions.  I will be publishing the blog post on this soon.

**Comment by artembilan** [comment]
Thank you @jxblum for explanation!

Looks like all you are saying is about SD **Kay**. What I mean that we can't upgrade here to SF 5.0 yet...

**Comment by sabbyanandan** [comment]
@jxblum: We are still on SF 4.x line - are there plans to backport the gemfire/geode compatibility?

**Comment by jxblum** [comment]
Hmmm, OK well I am not sure I am still following exactly, but SD **Kay** is based on _Spring Framework_ 5, which means both _Spring Data GemFire_ and _Spring Data Geode_ are based on SF 5.

**Comment by jxblum** [comment]
@sabbyanandan - so, both SD GemFire [**Ingalls**](https://github.com/spring-projects/spring-data-gemfire/blob/1.9.7.RELEASE/gradle.properties#L18) and SD Geode [1.0.0.INCUBATING-RELEASE](https://github.com/spring-projects/spring-data-gemfire/blob/1.0.0.APACHE-GEODE-INCUBATING-RELEASE/gradle.properties#L19) are based on SF 4.x.

However, it is not possible to have a version of _Spring Data Geode_ and _Spring Data GemFire_ that are compatible **before Kay** because GemFire/Geode (not _Spring_) changed their packaging.

You see, the version of SD GemFire that was based on SF 4.x is also [based on GF 8.2.6](https://github.com/spring-projects/spring-data-gemfire/blob/1.9.7.RELEASE/gradle.properties#L5), which is not source/binary compatible with Apache Geode since Pivotal GemFire 8.2.x had not been based on Apache Geode yet.  GemFire 8.2.2+ is on-the-wire/protocol compatible with Pivotal GemFire 9.x servers though.

**Comment by jxblum** [comment]
If we had released a SD line between **Ingalls** and **Kay** (which we had a branch for at one time (was SDG 1.10.x) with no intention of doing anything at all with it), then we could've had a SD GemFire based on SF 4.x and GemFire 9.0, which would be compatible with SD Geode.

**Comment by sabbyanandan** [comment]
If I'm interpreting this correctly, we _cannot_ have the existing sink interact with the latest GF/Geode until the app itself is refactored to SF 5.x/Boot 2.x stack. Did I get that right?

**Comment by jxblum** [comment]
Yes, that is correct.  It is 1 or the other.

It is not currently possible to support both Apache Geode (with SD Geode) and Pivotal GemFire (with SD GemFire) prior to SD Kay, simultaneously (not without jumping through code hoops, primarily because the package namespace in GemFire/Geode are different prior to GemFire 9, which will affect your imports and runtime class resolution).

Hope this helps.
